### ISSUE TITLE
Weird behaviour using llama 3.1 through Jlama

### ISSUE THREAD

**Issue by mariofusco** [tjake/Jlama#106]
This issue is probably not related with Jlama, but only with the kind of models that I'm using, but it would be great to have some clarification on this.

I'm trying to reconfigure [this example](https://github.com/mariofusco/quarkus-drools-llm?tab=readme-ov-file#the-airline-chatbot-example) in my toy project to have a version that works also with Jlama. Using Ollama with the [llama 3.1 8b](https://ollama.com/library/llama3.1) model I can achieve [this kind](https://github.com/mariofusco/quarkus-drools-llm/blob/main/images/refund.png) of interaction. 

With Jlama I'm using the [Meta-Llama-3.1-8B-Instruct-Jlama-Q4](https://huggingface.co/tjake/Meta-Llama-3.1-8B-Instruct-Jlama-Q4) which I believe should more or less equivalent to the one I used with Ollama, but I'm getting a very different and to me quite surprising result like this.

![image](https://github.com/user-attachments/assets/0adefdd2-facf-4846-b85f-6e90a882d12a)

The complete request generating that response is 

```
Request: [SystemMessage { text = "You are a chat bot of an airline company. Your goal is asking questions to gather information
about a customer
" }, UserMessage { name = null contents = [TextContent { text = "Ask question to the customer regarding his name and age, also replying to his message 'hi'
" }] }]
```

Is this sort of weird LLM internal conversation something caused by the model that I'm using or triggered by Jlama integration? And in the first case could you please suggest a model that could better fit my needs?

**Comment by tjake** [comment]
Hi @mariofusco 

Can you help me understand how to build your project? It seems I need the repository that has `drools-quarkus` 10.0.0 ?

**Comment by tjake** [comment]
Could you try it with `tjake/Llama-3.1-8B-Instruct-JQ4` ?

**Comment by mariofusco** [comment]
> Can you help me understand how to build your project? It seems I need the repository that has `drools-quarkus` 10.0.0 ?

Unfortunately you can't, that release is not out yet (we moved Drools under the Apache Foundation and having tons of more political rather than technical problem to finally put out the release). I will create a simplified version that doesn't require Drools and keep you posted.

**Comment by mariofusco** [comment]
> Could you try it with `tjake/Llama-3.1-8B-Instruct-JQ4` ?

This model works exactly as I expected (and with performances comparable to Ollama), great job!

Can you please explain the differences between this model and the other one that I attempted to use? Thanks again.

![image](https://github.com/user-attachments/assets/7903d44b-394b-4887-99df-01f910a85182)

**Comment by tjake** [comment]
> Can you please explain the differences between this model and the other one that I attempted to use? 

Well that old 3.1 may have had a bad prompt template (the model owner fixes bugs over time)  Also, I've added support for better float type combinations so the lossiness of quantization isn't as high.  Converting to and from BF16 -> Q4 -> F32 etc.

As for granite and other models, it really comes down to how well the model was fine tuned and the quality of the underlying training data.  One thing to try is to lower the temperature if which should reduce halucinations.

Did you see the same breakdown between those models in ollama too?

**Comment by mariofusco** [comment]
> As for granite and other models, it really comes down to how well the model was fine tuned and the quality of the underlying training data. One thing to try is to lower the temperature if which should reduce halucinations.

I'm already using temperature 0.

> Did you see the same breakdown between those models in ollama too?

To be honest I haven't tried Granite models with Ollama. I will and at this point I expect similar results to the ones produced by Jlama.

**Comment by tjake** [comment]
Ok, gonna close this then.
