### ISSUE TITLE
is that ment to be a cli tool, or can I integrate it with another java application, without using cli?

### ISSUE THREAD

**Issue by benayat** [tjake/Jlama#12]

**Comment by tjake** [comment]
Yes, it can be used directly, the cli is just a helper.  Once I push to maven I will include a sample app.

**Comment by tjake** [comment]
You can use `mvn install` for now

**Comment by benayat** [comment]
I don't understand why you closed this as "completed", since maven install won't tell me how to integrate it into my app

**Comment by tjake** [comment]
Added sample app into readme
