### ISSUE TITLE
Add Support to ChatMemory

### ISSUE THREAD

**Issue by DumiJDev** [tjake/Jlama#121]
Hi, I think that **ChatMemory** is a good feature to add, now I need implementing to each project, but a native support would be awesome.

**Comment by tjake** [comment]
Hi @DumiJDev 

Jlama already supports this via the sessionID passed to generate.  Basically the conversation continues from the last generated token

**Comment by DumiJDev** [comment]
For example, I need that chat memory cache the 10 or 20 messages between me and assistant.

**Comment by tjake** [comment]
You're saying you need to retrieve the actual messages?  Can you explain why?  

The sessionId, as I explained above, lets you avoid having to send in the old messages every time you send a new message.

**Comment by DumiJDev** [comment]
The assistant lose the context with few messages, and produce wrong responses, e.g, I say, ask about previous message, and assistant create a new context.

I may be making a mistake in my implementation, I'll try again here.
