### ISSUE TITLE
Add new generate method

### ISSUE THREAD

**Issue by DumiJDev** [tjake/Jlama#122]
Sometimes we need to generate response without pass a listener/callback function as last argument.

Actual: 

`Response generate(
        UUID session,
        PromptContext promptContext,
        float temperature,
        int ntokens,
        BiConsumer<String, Float> onTokenWithTimings
    );`

Suggest:

`Response generate(
        UUID session,
        PromptContext promptContext,
        float temperature,
        int ntokens
    );`

We don't often need a BiConsumer.

**Comment by tjake** [comment]
Sure, that would clean it up.  Also you don't need a session if you are passing along the full chat memory each time.

**Comment by DumiJDev** [comment]
Yes, it'd be interesting.
