### ISSUE TITLE
streaming server support?

### ISSUE THREAD

**Issue by kevintanhongann** [tjake/Jlama#20]
Is there a way to run and expose an API streaming server compatible with OpenAI API specifications?

**Comment by tjake** [comment]
Probably, here's the current API call for chat

https://github.com/tjake/Jlama/blob/main/jlama-cli/src/main/java/com/github/tjake/jlama/cli/serve/GenerateResource.java

**Comment by phact** [comment]
I want this feature too

**Comment by geoand** [comment]
I am pretty sure that this would (at least) require `Generator#generate` to be enhanced with a callback that is called when the generation is complete.

**Comment by phact** [comment]
You mean for stream=false?

**Comment by geoand** [comment]
For both :)

**Comment by phact** [comment]
working PR here https://github.com/tjake/Jlama/pull/23
