### ISSUE TITLE
Apple Silicon native compilation

### ISSUE THREAD

**Issue by sydneypdx** [tjake/Jlama#40]
To make this work for me, I had to get the apple silicon version of jextract (Java 21) and add this to bin/jextract script:

JLINK_VM_OPTIONS=--enable-native-access=org.openjdk.jextract

and make sure the resulting library was "libjlama.dynlib" and in the java_library_path when running the app and comment out all of the test code in the main pom.xml (though I'm working off an older snapshot, so maybe the junits work now for Apple M2).

**Comment by tjake** [comment]
You shouldn't run the jexract script. That's just for development.

The jlama-native module builds the native lib.
