### ISSUE TITLE
Dependency Conflict with `com.google.guava:guava` in `jlama-core`

### ISSUE THREAD

**Issue by PrimosK** [tjake/Jlama#46]
While addressing [langchain4j issue #1506](https://github.com/langchain4j/langchain4j/issues/1506), I encountered a dependency conflict related to `com.google.guava:guava` (when enabling Maven enforcer plugin):

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce) on project langchain4j-jlama:
[ERROR] Rule 0: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
[ERROR] Failed while enforcing releasability.
[ERROR]
[ERROR] Dependency convergence error for com.google.guava:guava:jar:32.0.1-jre paths to dependency are:
[ERROR] +-dev.langchain4j:langchain4j-jlama:jar:0.34.0-SNAPSHOT
[ERROR]   **+-com.github.tjake:jlama-core:jar:0.2.1:compile**
[ERROR]     +-com.google.guava:guava:jar:32.0.1-jre:compile
[ERROR] and
[ERROR] +-dev.langchain4j:langchain4j-jlama:jar:0.34.0-SNAPSHOT
[ERROR]   +**-com.github.tjake:jlama-core:jar:0.2.1:compile**
[ERROR]     +-com.hubspot.jinjava:jinjava:jar:2.7.2:compile
[ERROR]       +-com.google.guava:guava:jar:31.1-jre:compile

There are actually two approaches to resolve this:

1. Excluding `com.google.guava:guava` from `com.hubspot.jinjava:jinjava` as `com.google.guava:guava` is explicitly defined.

2. Avoid explicitly including `com.google.guava:guava` since it is already a transitive dependency of `com.hubspot.jinjava:jinjava`.

Would you be able to provide guidance or consider making this adjustment in the `jlama-core` project?

If needed, I can also open a pull request myself; I would just need a few pointers on which approach to proceed with...

Thanks for your attention to this issue!

**Comment by tjake** [comment]
Hi!
Thanks for the report.

I'd prefer option 1.  If you'd be willing to make the PR I would much appreciate!
