### ISSUE TITLE
Create stand alone downloadable cli for all platforms

### ISSUE THREAD

**Issue by tjake** [tjake/Jlama#47]
Based on general user issues I should make downloadable artifacts vs asking people to build.  Ive experimented with jpackage and seems to work well, though one day it should be graalvm

**Comment by kdhrubo** [comment]
So you mean a downloadable CLI that calls out to the API server running remote. Pretty much like docker or K8S?

**Comment by tjake** [comment]
The downloadable cli would *BE* the api server running models

**Comment by tjake** [comment]
@maxandersen I haven't used jbang before but it sure looks interesting.  I can put everything in maven sure.

**Comment by tjake** [comment]
@maxandersen jbang rocks!  I've added a script https://github.com/tjake/Jlama/blob/main/jlama.java and updated the readme, pushing to maven central then it'll work
