### ISSUE TITLE
Error starting  jlama

### ISSUE THREAD

**Issue by AdamBien** [tjake/Jlama#62]
After initial installation with jbang I get:

> jlama
---

06:09:04.959 [main] WARN com.github.tjake.jlama.tensor.operations.TensorOperationsProvider -- Error loading native operations
java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/github/tjake/jlama/tensor/operations/cnative/NativeSimd (class file version 65.65535). Try running with '--enable-preview'
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.github.tjake.jlama.tensor.operations.NativeTensorOperations.<clinit>(NativeTensorOperations.java:38)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at com.github.tjake.jlama.tensor.operations.TensorOperationsProvider.pickFastestImplementation(TensorOperationsProvider.java:55)
	at com.github.tjake.jlama.tensor.operations.TensorOperationsProvider.<init>(TensorOperationsProvider.java:46)
	at com.github.tjake.jlama.tensor.operations.TensorOperationsProvider.get(TensorOperationsProvider.java:36)
	at com.github.tjake.jlama.cli.JlamaCli.<clinit>(JlamaCli.java:31)
	at jlama.main(jlama.java:22)
06:09:04.963 [main] WARN com.github.tjake.jlama.util.MachineSpec -- Java SIMD Vector API *not* available. Add --add-modules=jdk.incubator.vector to your JVM options

---

I'm using:

 java -version
openjdk version "21" 2023-09-19 LTS

(Apple M3)

**Comment by tjake** [comment]
This shouldn’t be happening. @maxanderson could you take a look ?

**Comment by maxandersen** [comment]
never mind - figured what most likely is going on. 

@AdamBien please check what `jbang --version` says - my guess is you are running a quite old jbang version. one released before preview support was added, i.e. in 2020 https://github.com/jbangdev/jbang/issues/31 

you might even be running jbang older than when it could selfupdate.

try run `jbang version --update` and if updates it should fix it self; if not you'll want to remove that jbang and reinstall it to newer release.

**Comment by tjake** [comment]
Thanks for checking!

**Comment by jaswanth-7099** [comment]
hi i am trying to run the tjake model using langchain4j locally.
the models able to generate responses but taking too much time generating responses.
while running in spring i got the issuse with native library is not loaded.

"""
c.g.t.j.t.operations.util.JarSupport     : jlama-native shared library not found
.g.t.j.t.o.TensorOperationsProvider     : Native operations not available. Consider adding 'com.github.tjake:jlama-native' to the classpath
 c.g.t.j.t.o.TensorOperationsProvider     : Using Panama Vector Operations (OffHeap)

""""

"""this is the pom.xml that i am using 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.3</version>
		<relativePath /> 
	</parent>
	<groupId>com</groupId>
	<artifactId>tablesaw</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>excel</name>
	<description>Demo project for Spring Boot</description>
	<url />
	<licenses>
		<license />
	</licenses>
	<developers>
		<developer />
	</developers>
	<scm>
		<connection />
		<developerConnection />
		<tag />
		<url />
	</scm>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>1.0.1</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-jlama</artifactId>
			<version>1.0.1-beta6</version>
		</dependency>
		<dependency>
			<groupId>com.github.tjake</groupId>
			<artifactId>jlama-native</artifactId>
			<version>0.8.3</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.3</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>

		<dependency>
			<groupId>tech.tablesaw</groupId>
			<artifactId>tablesaw-core</artifactId>
			<version>0.43.1</version>
		</dependency>
		<dependency>
			<groupId>tech.tablesaw</groupId>
			<artifactId>tablesaw-excel</artifactId>
			<version>0.43.1</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
			<version>1.0.1-beta6</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
''''

can you please check this and give me suggestions for this.
