### ISSUE TITLE
JLama doesn't start on Apple M1 Max but works on M1 Ultra

### ISSUE THREAD

**Issue by stephanj** [tjake/Jlama#68]
I would like to run Jlama on my MacBookPro but running in the following issues:

Using following command on **Apple M1 Max** using Java Zulu21.28+85 

```
jlama restapi tjake/TinyLlama-1.1B-Chat-v1.0-Jlama-Q4 --auto-download
```

Gives the following error:

![image](https://github.com/user-attachments/assets/2db11250-6cc0-4586-9231-a54ffc2e540e)

However the same JVM on an **Apple M1 Ultra** works! 

<img width="1857" alt="Screenshot 2024-10-14 at 13 51 43" src="https://github.com/user-attachments/assets/b87dd7c6-a332-4c64-a570-c83bc4656980">

```
public AbstractTensor quantize(AbstractTensor t, DType qtype, int offset, int length) {
        Preconditions.checkArgument(t.dims() == 2 && length % Q8ByteBufferTensor.BLOCK_SIZE == 0);

        return switch (t.dType()) {
            case F32 -> switch (qtype) {
                case I8 -> switch (vectorType) {
                    case AVX_512 -> quantizeQ8_512((FloatBufferTensor) t, offset, length);
                    case AVX_256 -> quantizeQ8_256((FloatBufferTensor) t, offset, length);
                    case ARM_128 -> quantizeQ8_arm((FloatBufferTensor) t, offset, length);
==>                    default -> throw new UnsupportedOperationException();
                };
                case BF16 -> quantizeBF16((FloatBufferTensor) t, offset, length);
                default -> throw new UnsupportedOperationException();
            };
            case BF16 -> switch (qtype) {
                case I8 -> switch (vectorType) {
                    case AVX_512 -> quantizeBF16_Q8_512((BFloat16BufferTensor) t, offset, length);
                    case AVX_256 -> quantizeBF16_Q8_256((BFloat16BufferTensor) t, offset, length);
                    case ARM_128 -> quantizeBF16_Q8_arm((BFloat16BufferTensor) t, offset, length);
                    default -> throw new UnsupportedOperationException();
                };
                case F32 -> quantizeBF16_F32((BFloat16BufferTensor) t, offset, length);
                default -> throw new UnsupportedOperationException();
            };
            default -> throw new UnsupportedOperationException();
        };
    }
```

Suggestions would be much appreciated!  #ThanksInAdvance

**Comment by tjake** [comment]
👋 check to make sure you aren’t using Rosetta because that can cause this. Use an arm based jvm. See #25

**Comment by stephanj** [comment]
I'm running on arm with arm based JVM.  
BTW Guillaume had the same issue and never found a solution.  
Maybe you can share your settings of your MacBook Pro?  #Thanks

**Comment by stephanj** [comment]
First step was making sure I was using an arm enabled SDK : 

```
.sdkman/etc/config
```

Set roseta to false and save

```
sdkman_rosetta2_compatible=false
```

Now do a "sdk list java" and select an arm-compliant SDK,  but currently still no luck...

**Comment by stephanj** [comment]
The following command shows which OS_ARCH version the SDK is using: 

```
cat ~/.sdkman/candidates/java/current/release
```

x86_64 (which would explain why it's not working) on MacBook Pro
![image](https://github.com/user-attachments/assets/7294d1ae-b614-4ff5-b25e-40fa8a7386c8)

aarch64, which is what we want. 

<img width="1856" alt="GZ6zgVWW8AEVZqJ" src="https://github.com/user-attachments/assets/81df2f42-7a2b-4952-bd34-efee20cb8582">

So how can we force SDK to use aarch64?

**Comment by stephanj** [comment]
Not using SDKman but setting JAVA_HOME to an explicit ARM64 JDK solves it!  
In my example I've use Java 21 from Bellsoft and set JAVA_HOME to /Library/Java/JavaVirtualMachines/liberica-jdk-21.jdk/Contents/Home 

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/liberica-jdk-21.jdk/Contents/Home
```

then running 
```
jlama restapi tjake/TinyLlama-1.1B-Chat-v1.0-Jlama-Q4 --auto-download
```

runs the REST enabled JLama server! 

![image](https://github.com/user-attachments/assets/ec247138-9f76-413f-ba0e-ae98af135c14)
